# Generated by Django 4.1 on 2024-02-17 16:56

from django.db import migrations, models
import django.db.models.deletion
import hotels.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(editable=False)),
                ('updated_at', models.IntegerField()),
                ('title', models.CharField(help_text='Название города', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(editable=False)),
                ('updated_at', models.IntegerField()),
                ('title', models.CharField(help_text='Название отеля', max_length=255)),
                ('address', models.CharField(help_text='Адрес отеля', max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True, validators=[hotels.models.validate_international_phonenumber])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
